replication:
  connections:
    - type: postgresql
      uri: postgresql://powersync_repl:change_me@kasirgoplus-postgres:5432/kasirgoplus
      sslmode: disable

storage:
  type: mongodb
  uri: mongodb://mongo:27017/powersync_storage

port: 8080

sync_config:
  path: sync-config.yaml

client_auth:
  audience: ['powersync']
  jwks:
    keys:
      - kty: oct
        alg: 'HS256'
        kid: 'kasirgo-hs256'
        k: '<BASE64URL_DARI_JWT_SECRET_BACKEND>'

system:
  logging:
    level: info
    format: text
