config:
  edition: 3

streams:
  categories:
    auto_subscribe: true
    query: |
      SELECT * FROM categories
      WHERE tenant_id = auth.parameter('tenant_id')
        AND deleted_at IS NULL

  products:
    auto_subscribe: true
    query: |
      SELECT * FROM products
      WHERE tenant_id = auth.parameter('tenant_id')
        AND deleted_at IS NULL

  transactions:
    auto_subscribe: true
    query: |
      SELECT * FROM transactions
      WHERE tenant_id = auth.parameter('tenant_id')
        AND deleted_at IS NULL

  expenses:
    auto_subscribe: true
    query: |
      SELECT * FROM expenses
      WHERE tenant_id = auth.parameter('tenant_id')
        AND deleted_at IS NULL

  customers:
    auto_subscribe: true
    query: |
      SELECT * FROM customers
      WHERE tenant_id = auth.parameter('tenant_id')
        AND deleted_at IS NULL

  discounts:
    auto_subscribe: true
    query: |
      SELECT * FROM discounts
      WHERE tenant_id = auth.parameter('tenant_id')
        AND deleted_at IS NULL
